export const operacijeByKat = [
  {
    titleHr: 'Koljeno',
    titleEn: 'Knee',
    id: 1,
    contentHr: [
      'Totalna endoproteza koljena (TEP)',
      'REVIZIJSKA TOTALNA ENDOPROTEZA KOLJENA',
      'Rekonstrukcija stražnjeg križnog ligamenta (PCL)',
      'REKONSTRUKCIJA PREDNJEG KRIŽNOG LIGAMENTA (ACL)',
      'Rekonstrukcija medijalnog patelofemoralnog ligamenta (MPFL)',
      'Primarna kompleksna totalna endoproteza koljena',
      'Parcijalna endoproteza koljena (PEP)',
      'MENISCEKTOMIJA I ŠAV MENISKA',
      'Medijalizacija i ventromedijalizacija patele',
      'Korektivna osteotomija ',
      'ARTROSKOPIJA KOLJENA',
    ],
    contentEn: [
      'Total Knee Arthroplasty (TKA)',
      'Total knee arthroplasty',
      'Reconstruction of the posterior cruciate ligament (PCL)',
      'Frontal cruciate ligament (ACL)',
      'Rekonstrukcija medijalnog patelofemoralnog ligamenta (MPFL)',
      'Primary complex total knee replacement',
      'Partial knee replacement (PKR)',
      'Medialization and Ventromedialization of the Patella',
      'Corrective osteotomy',
      'KNEE ARTHROSCOPY',
    ],
  },
  {
    titleHr: 'Kuk',
    titleEn: 'Hip',
    id: 2,
    contentHr: ['Totalna endoproteza kuka (TEP)', 'REVIZIJSKA TOTALNA ENDOPROTEZA KUKA'],
    contentEn: ['TOTAL HIP REPLACEMENT (THR)', 'Revision total hip arthroplasty'],
  },
  {
    titleHr: 'Rame',
    titleEn: 'Shoulder',
    id: 3,
    contentHr: ['TOTALNA ENDOPROTEZA RAMENA'],
    contentEn: ['Shoulder Endoprosthesis'],
  },
  {
    titleHr: 'Gležanj',
    titleEn: 'Ankle',
    id: 4,
    contentHr: ['ARTROSKOPIJA GLEŽNJA', 'ARTRODEZA GLEŽNJA '],
    contentEn: ['Ankle arthroscopy', 'ANKLE ARTHRODESIS'],
  },
  {
    titleHr: 'Tetive',
    titleEn: 'Tendons',
    id: 5,
    contentHr: ['Ruptura tetive kvadricepsa ', 'Ruptura tetive patele', 'Ruptura Ahilove tetive'],
    contentEn: ['Quadriceps Tendon Rupture', 'Achilles tendon rupture', 'Achilles tendon rupture'],
  },
  {
    titleHr: 'Liječenje prijeloma',
    titleEn: 'Fracture Treatment',
    id: 6,
    contentHr: ['OSTEOSINTEZA '],
    contentEn: ['KNEE ARTHROSCOPY'],
  },
  {
    titleHr: 'Ortobiologija',
    titleEn: 'Orthobiology',
    id: 7,
    contentHr: [
      'Viskosuplementacija',
      'Autotransplantacija hrskavice',
      'Plazma obogaćena trombocitima (PRP)',
      'Matične stanice – Stromalna vaskularna frakcija (SVF)',
    ],
    contentEn: [
      'Viscosupplementation',
      'Cartilage autotransplantation',
      'Platelet-Rich Plasma (PRP)',
      'Stem cells - Stromal Vascular Fraction (SVF)',
    ],
  },
];
