import type { Metadata } from 'next';

import './globals.scss';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Firs = localFont({
  src: [
    { path: '../../public/fonts/tt_firs_neue/TT Firs Neue Trial Regular.ttf', weight: '400' },
    { path: '../../public/fonts/tt_firs_neue/TT Firs Neue Trial Medium.ttf', weight: '500' },
    { path: '../../public/fonts/tt_firs_neue/TT Firs Neue Trial Bold.ttf', weight: '700' },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='w-full h-full bg-white'>
      <body className={`${Firs.className} w-full h-full bg-white`}>{children}</body>
    </html>
  );
}
